### ISSUE TITLE
Transfer the repo

### ISSUE THREAD

**Issue by zbraniecki** [zbraniecki/pluralrules#28]
Hi @unclenachoduh - since I'm the de-facto maintainer of the crate now, can you please transfer the repo to me? Thank you!

**Comment by unclenachoduh** [comment]
I tried to transfer the repo to you, but the action was blocked because you already have a repo called pluralrules.

I'm happy to transfer the repo, just let me know where/when to transfer it.

**Comment by zbraniecki** [comment]
done!

**Comment by unclenachoduh** [comment]
I requested the transfer.

**Comment by zbraniecki** [comment]
Thank you! Fixed!
