### ISSUE TITLE
1.1.0 Breaks Semver

### ISSUE THREAD

**Issue by topokel** [zbraniecki/pluralrules#29]
Commit 41500c50e38a14cdb4b3614c2400efca735af735 *modifies* some public api's, which is fine going from 0.1.0 to 0.2.0 for example, but Semver, or more specifically caret dependencies in rust, assume that "stable" (read: 1.x.x and greater) libraries will not *change* their existing API's in minor versions. Therefor crates that depend on intl_pluralrules with `version = "1.0"` or even `version = "1.0.0"` would still break with the publishing of `1.1.0`. Check the ["Caret Requirements" section of The Cargo Book's guide on specifying dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements) (all version requirements without operators are interpreted as caret requirements).

**Comment by zbraniecki** [comment]
oh, thank you for reporting that! I was not aware of this. :(

I'll likely yank this version tomorrow and plan to release it as 2.0.

**Comment by zbraniecki** [comment]
Yanked and will release soon as 2.0
