### ISSUE TITLE
Fails to build using tarpaulin 0.14.+

### ISSUE THREAD

**Issue by wyattjsmith1** [zbraniecki/pluralrules#35]
Currently, this project fails to compile when running tarpaulin:
```
   {Other deps compiling}
   Compiling intl_pluralrules v7.0.0
error: could not compile `intl_pluralrules`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
[ERROR tarpaulin] Failed to compile tests! Error: cannot find attribute `skip` in this scope
Error: "Failed to compile tests! Error: cannot find attribute `skip` in this scope"
```

According to https://github.com/xd009642/tarpaulin/issues/505, a similar thing happened for https://github.com/time-rs/time. It appears as though the tarpaulin `skip` attribute is deprecated. This is affecting any project pulling this crate and using tarpaulin 0.14.+.

**Comment by zbraniecki** [comment]
should be fixed in master!
